version: "2"

services:
  nodeosd:
    image: eosio/eos:v1.4.3
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  branch: master

    command: /opt/eosio/bin/nodeosd.sh --verbose-http-errors --max-transaction-time=1000 --data-dir /opt/eosio -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --access-control-allow-origin "*"
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    cap_add:
      - IPC_LOCK
    expose:
      - "8888"

# --wallet-dir /opt/eosio
  keosd:
    image: eosio/eos:v1.4.3
    command: /opt/eosio/bin/keosd --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    ports:
      - 8900:8900
    links:
      - nodeosd
